config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#top'
  # resources :static_pages
  # root to: 'users#index'
  resources :users, only: [:new, :create, :index]

  get '/login' , to: 'user_sessions#new',  :as => :login
  post '/login' , to: 'user_sessions#create'
  delete '/logout' , to: 'user_sessions#destroy', :as => :logout
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :email, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login

    private
    
    def not_authenticated
        redirect_to login_path, alert: "Please login first"
    end

    # def current_user
        # @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    # end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    skip_before_action :require_login
    def top
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to root_path, notice: 'Login successful'
    else
      flash.now[:alert] = 'Login failed'
      render :new
    end
  end

  def destroy
    logout
    redirect_back_or_to root_path, notice: 'Logged out!'
  end

  private
  def session_params
    params.require(:user).permit(:last_name, :first_name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create] # this should only be used if you are allowing users to register themselves.

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by(id: params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    # binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: 'User was successfully created'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  # def update
    # respond_to do |format|
      # if @user.update(user_params)
        # format.html { redirect_to @user, notice: 'User was successfully updated.' }
        # format.json { render :show, status: :ok, location: @user }
      # else
        # format.html { render :edit }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      # end
    # end
  # end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  private
    def user_params
      params.require(:user).permit(:last_name, :first_name, :email, :password, :password_confirmation, :salt)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RunteqNormal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>



  
  </head>

  <body>
    <% if logged_in? %>
      <%=render 'shared/header' %>
    <% else %>
      <%=render 'shared/before_login_header' %>  
    <% end %>

    <%= yield %>
    <%=render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <a class='navbar-brand' href='/'>
      <%= image_tag 'logo.png' %>
    </a>
    
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to "ログイン", login_path, class: 'navbar-brand' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright © 2019. RUNTEQ</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ml-auto main-nav align-items-center'>
        <li class='nav-item dropdown dropdown-slide'>
          <a href='#' class='nav-link dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>
            掲示板
          </a>

          <ul class='dropdown-menu dropdown-menu-right'>
            <li><%= link_to "掲示板一覧", "#", class: 'dropdown-item' %></li>
            <li><%= link_to "掲示板作成", "#", class: 'dropdown-item' %></li>
          </ul>
        </li>

        <li class='nav-item'>
          <%= link_to "ブックマーク一覧", "#", class: 'nav-link' %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <a href='#' class='nav-link' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' id='header-profile'>
            <%= image_tag 'sample.jpg', class: 'rounded-circle mr15', width: 40, height: 40 %>
          </a>
          
          <ul class='dropdown-menu dropdown-menu-right'>
            <div class='dropdown-item'>らんてっく たろう</div>
            <div class='dropdown-divider'></div>
            <li><%= link_to "プロフィール", "#", class: 'dropdown-item' %></li>
            <li><%= link_to "ログアウト", logout_path, class: 'dropdown-item', method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/static_pages/top.html.erb
<div class='top-wrapper'>
  <div class='top-inner-text'>
    <h1>RUNTEQ BOARD APP</h1>
  </div>
</div>

app/views/user_sessions/_form.html.erb
<%= form_with url: login_path do |f| %>
    <div class="field">
        <%= f.label :email %><br/>
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %><br/>
        <%= f.password_field :password %>
    </div>
    <div class="actions">
        <%= f.submit "Login" %>
    </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container">
    <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
        <h1>ログイン</h1>
        <%= form_with model: @user, url: login_path, local: true do |f| %>
        <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control"  %>
        </div>
        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control"  %>
        </div>
        
        <div class="actions">
            <%= f.submit "ログイン", class: "btn btn-primary" %>
        </div>
        <% end %>
            <div class='text-center'>
                <%= link_to "登録ページへ", new_user_path %><br>
                <a href="#">パスワードをお忘れの方はこちら</a>
            </div>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :crypted_password %>
    <%= form.text_field :crypted_password %>
  </div>

  <div class="field">
    <%= form.label :salt %>
    <%= form.text_field :salt %>
  </div>

<div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password %>
</div>
<div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', users %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
        <h1>ユーザー登録</h1>
        <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control"  %>
        </div>
        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control"  %>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: "form-control"  %>    
        </div>

        <div class='text-center'>
            <%= f.submit '登録', class: "btn btn-primary" %>  
        </div>
        <%= link_to "ログインページへ", login_path %>
    </div>
</div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>